# Modified travis.yml set-up for the new native R support on Travis CI

language: r

r_build_args: " --compact-vignettes=gs+qpdf"
r_check_args: " --as-cran"

notifications:
  email:
    on_success: change
    on_failure: change
