# Modified travis.yml set-up for the new native R support on Travis CI

language: r

sudo: required

apt_packages:
  - qpdf

r_binary_packages:
  - testthat
  - vegan
  - mgcv
  - MASS
  - brglm
  - princurve
  - Rcpp
  - crayon
  - lazyeval
  - jsonlite
  - htmltools

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: " --compact-vignettes=gs+qpdf"
r_check_args: " --as-cran"

notifications:
  email:
    on_success: change
    on_failure: always