<?php
   echo "
      <div id=\"footer\">
			
			<p>
			&copy; 2008-10 <strong>Gavin L. Simpson</strong> | 
			Design by: <a href=\"http://www.styleshout.com/\">styleshout</a> | 
			Valid <a href=\"http://validator.w3.org/check?uri=referer\">XHTML</a> | 
			<a href=\"http://jigsaw.w3.org/css-validator/check/referer\">CSS</a>
			
   		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			
			<a href=\"index.html\">Home</a>&nbsp;|&nbsp;
   		<a href=\"index.html\">Sitemap</a>&nbsp;|&nbsp;
	   	<a href=\"http://r-forge.r-project.org/export/rss_sfnews.php?group_id=69\">RSS Feed</a>
   		</p>
				
		</div>
   ";
?>