<?php
    echo "
<head>

<meta name=\"Description\" content=\"{$DESCRIPTION}\" />
<meta name=\"Keywords\" content=\"{$KEYWORDS}\" />
<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />
<meta name=\"Distribution\" content=\"Global\" />
<meta name=\"author\" content=\"{$AUTHOR}\"/>
<meta name=\"Robots\" content=\"index,follow\" />

<link rel=\"stylesheet\" href=\"images/Refresh.css\" type=\"text/css\" />

<title>{$TITLE}</title>

</head>
    ";
?>