<?php
   echo "
   <div  id=\"menu\">
			<ul>
				<li id=\"current\"><a href=\"index.php\">Home</a></li>
				<li><a href=\"news.php\">Project News</a></li>
				<li><a href=\"downloads.php\">Downloads</a></li>
				<li><a href=\"documentation.php\">Documentation</a></li>
				<li><a href=\"devel.php\">Development</a></li>
				<li><a href=\"support.php\">Support</a></li>	
			</ul>
		</div>
   ";
?>