<?php
   echo "
   <div  id=\"menu\">
			<ul>
				<li id=\"current\"><a href=\"index.html\">Home</a></li>
				<li><a href=\"news.html\">Project News</a></li>
				<li><a href=\"downloads.html\">Downloads</a></li>
				<li><a href=\"documentation.html\">Documentation</a></li>
				<li><a href=\"devel.html\">Development</a></li>
				<li><a href=\"support.html\">Support</a></li>	
			</ul>
		</div>
   ";
?>