<?php
    $stable_version = "0.6-6";
    echo "
         <div id=\"sidebar\">
				<h1>Downloads</h1>
				<div class=\"left-box\">
					<ul class=\"sidemenu\">
   					    <li><a href=\"http://cran.r-project.org/web/packages/analogue/index.html\">Stable version ({$stable_version})</a></li>
						<li><a href=\"http://r-forge.r-project.org/R/?group_id=69\">Development version</a></li>
  					</ul>	
				</div>
			
				<h1>Related R Packages</h1>
				<div class=\"left-box\">
					<ul class=\"sidemenu\">
   					    <li><a href=\"http://cran.r-project.org/web/packages/vegan/index.html\">Vegan</a></li>
  					</ul>	
				</div>
				
				<h1>R-Forge Page</h1>
				<div class=\"left-box\">
					<ul class=\"sidemenu\">
   					    <li><a href=\"http://r-forge.r-project.org/projects/analogue/\">analogue R-Forge page</a></li>
  					</ul>	
				</div>
				
			</div>
    ";
?>